/* 手元でだけ実験場に出す、作りかけのゲーム。

   このファイルは `_` で始まるので GitHub Pages には出ません。
   サイトの index.html は、localhost で開いたときだけこれを読みます。
   （公開サイトでは読みに行かないので、名前もソースに残りません）

   足すのは games/_tools/new.js、公開は games/_tools/publish.js が面倒を見ます。 */
window.DRAFT_GAMES = [
  {
    "type": "lab",
    "tags": [],
    "id": "gojuon-roulette",
    "title": "50音ルーレット",
    "year": 2026,
    "date": "2026-09-23",
    "plays": null,
    "url": "",
    "img": "games/_gojuon-roulette/img/thumb.webp",
    "play": "games/_gojuon-roulette/index.html",
    "full": true,
    "catch": "50音に賭けるルーレット"
  },
  {
    "type": "lab",
    "tags": [],
    "id": "wiki-bingo",
    "title": "Wikipediaビンゴ",
    "year": 2026,
    "date": "2026-09-23",
    "plays": null,
    "url": "",
    "img": "games/_wiki-bingo/img/thumb.webp",
    "play": "games/_wiki-bingo/index.html",
    "full": true,
    "catch": "Wikipediaの記事でかなビンゴ"
  },
  {
    "type": "lab",
    "tags": [],
    "id": "brute-escape",
    "title": "総当たり脱出ゲーム",
    "year": 2026,
    "date": "2026-09-27",
    "plays": null,
    "url": "",
    "img": "games/_brute-escape/img/thumb.webp",
    "play": "games/_brute-escape/index.html",
    "full": true,
    "catch": ""
  },
  {
    "type": "lab",
    "tags": [],
    "id": "gazou-meiro",
    "title": "画像迷路",
    "year": 2026,
    "date": "2026-10-03",
    "plays": null,
    "url": "",
    "img": "games/_gazou-meiro/img/thumb.webp",
    "play": "games/_gazou-meiro/index.html",
    "full": true,
    "catch": "画像の線から迷路を作る"
  },
  {
    "type": "lab",
    "tags": [],
    "id": "qr-meiro",
    "title": "QRコード迷路",
    "year": 2026,
    "date": "2026-10-03",
    "plays": null,
    "url": "",
    "img": "games/_qr-meiro/img/thumb.webp",
    "play": "games/_qr-meiro/index.html",
    "full": true,
    "catch": "QRコードの中を歩いて抜ける"
  },
  {
    "type": "lab",
    "tags": [],
    "id": "melody-meiro",
    "title": "メロディ迷路",
    "year": 2026,
    "date": "2026-10-03",
    "plays": null,
    "url": "",
    "img": "games/_melody-meiro/img/thumb.webp",
    "play": "games/_melody-meiro/index.html",
    "full": true,
    "catch": "正しい道を進むと曲が進む"
  },
  {
    "type": "lab",
    "tags": [],
    "id": "pixel-meiro",
    "title": "1ピクセル迷路",
    "year": 2026,
    "date": "2026-10-04",
    "plays": null,
    "url": "",
    "img": "games/_pixel-meiro/img/thumb.webp",
    "play": "games/_pixel-meiro/index.html",
    "full": true,
    "catch": ""
  },
  {
    "type": "lab",
    "tags": [],
    "id": "gaso-kuzushi",
    "title": "画素くずし",
    "year": 2026,
    "date": "2026-10-04",
    "plays": null,
    "url": "",
    "img": "games/_gaso-kuzushi/img/thumb.webp",
    "play": "games/_gaso-kuzushi/index.html",
    "full": true,
    "catch": ""
  },
  {
    "type": "lab",
    "tags": [],
    "id": "gaso-amida",
    "title": "画素あみだ",
    "year": 2026,
    "date": "2026-10-04",
    "plays": null,
    "url": "",
    "img": "games/_gaso-amida/img/thumb.webp",
    "play": "games/_gaso-amida/index.html",
    "full": true,
    "catch": ""
  },
  {
    "type": "lab",
    "tags": [],
    "id": "meishoku",
    "title": "迷色",
    "year": 2026,
    "date": "2026-10-04",
    "plays": null,
    "url": "",
    "img": "games/_meishoku/img/thumb.webp",
    "play": "games/_meishoku/index.html",
    "full": true,
    "catch": ""
  },
  {"type":"lab","tags":[],"id":"mashimashi","title":"無限マシマシ","year":2026,"date":"2026-10-04","plays":null,"url":"","img":"games/_mashimashi/img/thumb.webp","play":"games/_mashimashi/index.html","full":true,"catch":"二郎系ラーメンを無限にマシ"},
];
